print("What is your name ?")
name = input()
print("What is your age ?")
age = int(input())
print("what is your country of orgin ?")
country = input()
print(name + " is " + age + " years old today ")
print(name + " is from " + country)